/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type RunsOverviewSectionButton = {
  text?: string
  link?: Link
}

export type Cta = {
  boldText?: string
  bodyText?: string
  button?: Button
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type FeatureCardImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "featureCard.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type FeaturesGridSection = {
  _type: 'featuresGridSection'
  heading: string
  cards?: Array<{
    image: FeatureCardImage
    heading: string
    body?: string
    _type: 'featureCard'
    _key: string
  }>
  cta?: Cta
}

export type IntroTextSection = {
  _type: 'introTextSection'
  quote: string
}

export type RunsOverviewSection = {
  _type: 'runsOverviewSection'
  eyebrow?: string
  heading?: string
  button?: RunsOverviewSectionButton
  runs?: 'upcomingRuns' | 'pastRuns' | 'allRuns'
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post'
  href?: string
  page?: PageReference
  post?: PostReference
  openInNewTab?: boolean
}

export type HeroAbout = {
  _type: 'heroAbout'
  heading: string
  subheading?: string
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
  stats?: Array<{
    value: string
    label: string
    _type: 'stat'
    _key: string
  }>
}

export type CallToAction = {
  _type: 'callToAction'
  eyebrow?: string
  heading: string
  body?: BlockContentTextOnly
  button?: Button
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  theme?: 'light' | 'dark'
  contentAlignment?: 'textFirst' | 'imageFirst'
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: BlockContent
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post'
        href?: string
        page?: PageReference
        post?: PostReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type Faq = {
  _id: string
  _type: 'faq'
  _createdAt: string
  _updatedAt: string
  _rev: string
  question: string
  answer: BlockContent
  category?: string
  orderRank?: string
}

export type LocationReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'location'
}

export type Run = {
  _id: string
  _type: 'run'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  location?: LocationReference
  date?: string
  distance?: number
  pace?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Location = {
  _id: string
  _type: 'location'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  address?: string
  latitude?: number
  longitude?: number
}

export type RunReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'run'
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  subtitle?: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
    | ({
        _key: string
      } & HeroAbout)
    | ({
        _key: string
      } & RunsOverviewSection)
    | ({
        _key: string
      } & IntroTextSection)
    | ({
        _key: string
      } & FeaturesGridSection)
  >
  heroGallery?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
  featuredRuns?: Array<
    {
      _key: string
    } & RunReference
  >
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type Navigation = {
  _id: string
  _type: 'navigation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  items?: Array<{
    label?: string
    link: Link
    _type: 'item'
    _key: string
  }>
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: PageReference
      post?: PostReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  heading: string
  subheading?: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
    | ({
        _key: string
      } & HeroAbout)
    | ({
        _key: string
      } & RunsOverviewSection)
    | ({
        _key: string
      } & IntroTextSection)
    | ({
        _key: string
      } & FeaturesGridSection)
  >
}

export type PersonReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'person'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  content?: BlockContent
  excerpt?: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: PersonReference
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | RunsOverviewSectionButton
  | Cta
  | SanityImageAssetReference
  | FeatureCardImage
  | FeaturesGridSection
  | IntroTextSection
  | RunsOverviewSection
  | PageReference
  | PostReference
  | Link
  | HeroAbout
  | CallToAction
  | InfoSection
  | BlockContentTextOnly
  | BlockContent
  | Button
  | Faq
  | LocationReference
  | Run
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Location
  | RunReference
  | HomePage
  | Navigation
  | Settings
  | Page
  | PersonReference
  | Post
  | Person
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: PageReference
      post?: PostReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
} | null

// Source: sanity/lib/queries.ts
// Variable: navigationQuery
// Query: *[_type == "navigation"][0] {    ...,    items[]{      ...,        link {      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      }    }  }
export type NavigationQueryResult = {
  _id: string
  _type: 'navigation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  items: Array<{
    label?: string
    link: {
      _type: 'link'
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page: string | null
      post: string | null
      openInNewTab?: boolean
    }
    _type: 'item'
    _key: string
  }> | null
} | null

// Source: sanity/lib/queries.ts
// Variable: getPageQuery
// Query: *[_type == 'page' && slug.current == $slug][0]{    _id,    _type,    name,    slug,    heading,    subheading,    "pageBuilder": pageBuilder[]{        ...,  _type == "callToAction" => {    ...,    button {      ...,        link {      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      }    }  },  _type == "infoSection" => {    content[]{      ...,      markDefs[]{        ...,          _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      }    }  },  _type == "featuresGridSection" => {    ...,    cta {      ...,      button {        ...,          link {      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      }      }    }  },    },  }
export type GetPageQueryResult = {
  _id: string
  _type: 'page'
  name: string
  slug: Slug
  heading: string
  subheading: string | null
  pageBuilder: Array<
    | {
        _key: string
        _type: 'callToAction'
        eyebrow?: string
        heading: string
        body?: BlockContentTextOnly
        button: {
          _type: 'button'
          buttonText?: string
          link: {
            _type: 'link'
            linkType?: 'href' | 'page' | 'post'
            href?: string
            page: string | null
            post: string | null
            openInNewTab?: boolean
          } | null
        } | null
        image?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        theme?: 'dark' | 'light'
        contentAlignment?: 'imageFirst' | 'textFirst'
      }
    | {
        _key: string
        _type: 'featuresGridSection'
        heading: string
        cards?: Array<{
          image: FeatureCardImage
          heading: string
          body?: string
          _type: 'featureCard'
          _key: string
        }>
        cta: {
          boldText?: string
          bodyText?: string
          button: {
            _type: 'button'
            buttonText?: string
            link: {
              _type: 'link'
              linkType?: 'href' | 'page' | 'post'
              href?: string
              page: string | null
              post: string | null
              openInNewTab?: boolean
            } | null
          } | null
        } | null
      }
    | {
        _key: string
        _type: 'heroAbout'
        heading: string
        subheading?: string
        images?: Array<{
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
          _key: string
        }>
        stats?: Array<{
          value: string
          label: string
          _type: 'stat'
          _key: string
        }>
      }
    | {
        _key: string
        _type: 'infoSection'
        heading?: string
        subheading?: string
        content: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
              listItem?: 'bullet' | 'number'
              markDefs: Array<{
                linkType?: 'href' | 'page' | 'post'
                href?: string
                page: string | null
                post: string | null
                openInNewTab?: boolean
                _type: 'link'
                _key: string
              }> | null
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
              markDefs: null
            }
        > | null
      }
    | {
        _key: string
        _type: 'introTextSection'
        quote: string
      }
    | {
        _key: string
        _type: 'runsOverviewSection'
        eyebrow?: string
        heading?: string
        button?: RunsOverviewSectionButton
        runs?: 'allRuns' | 'pastRuns' | 'upcomingRuns'
      }
  > | null
} | null

// Source: sanity/lib/queries.ts
// Variable: sitemapData
// Query: *[(_type == "page" || _type == "post" || _type == "run") && defined(slug.current)] | order(_type asc) {    "slug": slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<
  | {
      slug: string
      _type: 'page'
      _updatedAt: string
    }
  | {
      slug: string
      _type: 'post'
      _updatedAt: string
    }
  | {
      slug: string
      _type: 'run'
      _updatedAt: string
    }
>

// Source: sanity/lib/queries.ts
// Variable: allPostsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type AllPostsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
}>

// Source: sanity/lib/queries.ts
// Variable: morePostsQuery
// Query: *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type MorePostsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
}>

// Source: sanity/lib/queries.ts
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug] [0] {    content[]{    ...,    markDefs[]{      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }    }  },      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type PostQueryResult = {
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs: Array<{
          linkType?: 'href' | 'page' | 'post'
          href?: string
          page: string | null
          post: string | null
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }> | null
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
        markDefs: null
      }
  > | null
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: postPagesSlugs
// Query: *[_type == "post" && defined(slug.current)]  {"slug": slug.current}
export type PostPagesSlugsResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: pagesSlugs
// Query: *[_type == "page" && defined(slug.current)]  {"slug": slug.current}
export type PagesSlugsResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: upcomingRunsQuery
// Query: *[_type == "run" && defined(slug.current) && defined(date) && date >= now()] | order(date asc) {      _id,  title,  "slug": slug.current,  description,  image,  "location": location->{name, address},  date,  distance,  pace,  }
export type UpcomingRunsQueryResult = Array<{
  _id: string
  title: string
  slug: string
  description: string | null
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  location: {
    name: string
    address: string | null
  } | null
  date: string | null
  distance: number | null
  pace: string | null
}>

// Source: sanity/lib/queries.ts
// Variable: pastRunsQuery
// Query: *[_type == "run" && defined(slug.current) && defined(date) && date < now()] | order(date desc) {      _id,  title,  "slug": slug.current,  description,  image,  "location": location->{name, address},  date,  distance,  pace,  }
export type PastRunsQueryResult = Array<{
  _id: string
  title: string
  slug: string
  description: string | null
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  location: {
    name: string
    address: string | null
  } | null
  date: string | null
  distance: number | null
  pace: string | null
}>

// Source: sanity/lib/queries.ts
// Variable: runQuery
// Query: *[_type == "run" && slug.current == $slug] [0] {      _id,  title,  "slug": slug.current,  description,  image,  "location": location->{name, address},  date,  distance,  pace,  }
export type RunQueryResult = {
  _id: string
  title: string
  slug: string
  description: string | null
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  location: {
    name: string
    address: string | null
  } | null
  date: string | null
  distance: number | null
  pace: string | null
} | null

// Source: sanity/lib/queries.ts
// Variable: runPagesSlugs
// Query: *[_type == "run" && defined(slug.current)]  {"slug": slug.current}
export type RunPagesSlugsResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: faqsQuery
// Query: *[_type == "faq"] | order(orderRank asc) {    _id,    question,    answer,    category,  }
export type FaqsQueryResult = Array<{
  _id: string
  question: string
  answer: BlockContent
  category: string | null
}>

// Source: sanity/lib/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage"][0]{    _id,    _type,    title,    subtitle,    "pageBuilder": pageBuilder[]{        ...,  _type == "callToAction" => {    ...,    button {      ...,        link {      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      }    }  },  _type == "infoSection" => {    content[]{      ...,      markDefs[]{        ...,          _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      }    }  },  _type == "featuresGridSection" => {    ...,    cta {      ...,      button {        ...,          link {      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      }      }    }  },    },    "featuredRuns": featuredRuns[]->{        _id,  title,  "slug": slug.current,  description,  image,  "location": location->{name, address},  date,  distance,  pace,    },    ogImage,    ...  }
export type HomePageQueryResult = {
  _id: string
  _type: 'homePage'
  title: string
  subtitle?: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & FeaturesGridSection)
    | ({
        _key: string
      } & HeroAbout)
    | ({
        _key: string
      } & InfoSection)
    | ({
        _key: string
      } & IntroTextSection)
    | ({
        _key: string
      } & RunsOverviewSection)
  >
  featuredRuns?: Array<
    {
      _key: string
    } & RunReference
  >
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  _createdAt: string
  _updatedAt: string
  _rev: string
  heroGallery?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "settings"][0]': SettingsQueryResult
    '*[_type == "navigation"][0] {\n    ...,\n    items[]{\n      ...,\n      \n  link {\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n      }\n\n    }\n  }\n': NavigationQueryResult
    '\n  *[_type == \'page\' && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    "pageBuilder": pageBuilder[]{\n      \n  ...,\n  _type == "callToAction" => {\n    ...,\n    button {\n      ...,\n      \n  link {\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n      }\n\n    }\n  },\n  _type == "infoSection" => {\n    content[]{\n      ...,\n      markDefs[]{\n        ...,\n        \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n      }\n    }\n  },\n  _type == "featuresGridSection" => {\n    ...,\n    cta {\n      ...,\n      button {\n        ...,\n        \n  link {\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n      }\n\n      }\n    }\n  },\n\n    },\n  }\n': GetPageQueryResult
    '\n  *[(_type == "page" || _type == "post" || _type == "run") && defined(slug.current)] | order(_type asc) {\n    "slug": slug.current,\n    _type,\n    _updatedAt,\n  }\n': SitemapDataResult
    '\n  *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': AllPostsQueryResult
    '\n  *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': MorePostsQueryResult
    '\n  *[_type == "post" && slug.current == $slug] [0] {\n    content[]{\n    ...,\n    markDefs[]{\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n    }\n  },\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': PostQueryResult
    '\n  *[_type == "post" && defined(slug.current)]\n  {"slug": slug.current}\n': PostPagesSlugsResult
    '\n  *[_type == "page" && defined(slug.current)]\n  {"slug": slug.current}\n': PagesSlugsResult
    '\n  *[_type == "run" && defined(slug.current) && defined(date) && date >= now()] | order(date asc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  description,\n  image,\n  "location": location->{name, address},\n  date,\n  distance,\n  pace,\n\n  }\n': UpcomingRunsQueryResult
    '\n  *[_type == "run" && defined(slug.current) && defined(date) && date < now()] | order(date desc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  description,\n  image,\n  "location": location->{name, address},\n  date,\n  distance,\n  pace,\n\n  }\n': PastRunsQueryResult
    '\n  *[_type == "run" && slug.current == $slug] [0] {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  description,\n  image,\n  "location": location->{name, address},\n  date,\n  distance,\n  pace,\n\n  }\n': RunQueryResult
    '\n  *[_type == "run" && defined(slug.current)]\n  {"slug": slug.current}\n': RunPagesSlugsResult
    '\n  *[_type == "faq"] | order(orderRank asc) {\n    _id,\n    question,\n    answer,\n    category,\n  }\n': FaqsQueryResult
    '\n  *[_type == "homePage"][0]{\n    _id,\n    _type,\n    title,\n    subtitle,\n    "pageBuilder": pageBuilder[]{\n      \n  ...,\n  _type == "callToAction" => {\n    ...,\n    button {\n      ...,\n      \n  link {\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n      }\n\n    }\n  },\n  _type == "infoSection" => {\n    content[]{\n      ...,\n      markDefs[]{\n        ...,\n        \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n      }\n    }\n  },\n  _type == "featuresGridSection" => {\n    ...,\n    cta {\n      ...,\n      button {\n        ...,\n        \n  link {\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n      }\n\n      }\n    }\n  },\n\n    },\n    "featuredRuns": featuredRuns[]->{\n      \n  _id,\n  title,\n  "slug": slug.current,\n  description,\n  image,\n  "location": location->{name, address},\n  date,\n  distance,\n  pace,\n\n    },\n    ogImage,\n    ...\n  }\n': HomePageQueryResult
  }
}
